[tool.ruff]
select = ["E", "F", "I"]
exclude = [
  "build",
  "dist",
  "gamma/pre_exec.py"
]
line-length = 120

[tool.pyright]
include = ["api", "data_type", "extension", "gamma", "nlp", "test"]
exclude = ["gamma/pre_exec.py", "gamma/diffsteps.py", "gamma/intsteps.py"]
