name: kernel

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kernel
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Minor version same with Pyodide
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -c 'import nltk; nltk.download("words")'
      - name: Check code quality
        run: |
          ruff .
          pyright
      - name: Run integration tests
        run: |
          pytest --cov=gamma --cov=extension --cov=nlp -n auto test
