name: node

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - name: Install dependencies
        run: |
          npm i
      - name: Run lint
        run: |
          npm run lint
      - name: Build
        run: |
          npm run build
